package vip.coolcode.account.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone_number
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.confirmed_and_active
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private Boolean confirmedAndActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password_hash
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.photo_url
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    private String photoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone_number
     *
     * @return the value of account.phone_number
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone_number
     *
     * @param phoneNumber the value for account.phone_number
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.confirmed_and_active
     *
     * @return the value of account.confirmed_and_active
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public Boolean getConfirmedAndActive() {
        return confirmedAndActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.confirmed_and_active
     *
     * @param confirmedAndActive the value for account.confirmed_and_active
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setConfirmedAndActive(Boolean confirmedAndActive) {
        this.confirmedAndActive = confirmedAndActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password_hash
     *
     * @return the value of account.password_hash
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password_hash
     *
     * @param passwordHash the value for account.password_hash
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash == null ? null : passwordHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.photo_url
     *
     * @return the value of account.photo_url
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.photo_url
     *
     * @param photoUrl the value for account.photo_url
     *
     * @mbg.generated Wed Nov 18 10:23:25 CST 2020
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }
}